language: node_js
node_js:
  - "12.9.0"
cache:
  directories:
    - node_modules
script:
  - echo 'Installing Deps!'
  - npm install
  - echo 'Testing!'
  - npm run test
build:
  - echo 'Building Project'
  - npm run build
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token "$FIREBASE_TOKEN"
